name: CI/CD Pipeline - Static Website Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git SHA for tagging
      id: vars
      run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Secret Scanning with Gitleaks (SCA)
      uses: gitleaks/gitleaks-action@v2
      with:
        args: "--verbose --redact --exit-code 1"

    - name: SonarCloud Scan (SAST)
      run: |
        echo "Running SonarCloud scan"
        docker run --rm \
          -e SONAR_SCANNER_OPTS="-Dsonar.login=${{ secrets.SONAR_TOKEN }}" \
          -e SONAR_PROJECT_KEY=${{ secrets.SONAR_PROJECT_KEY }} \
          -e SONAR_ORGANIZATION=${{ secrets.SONAR_ORG }} \
          -v $(pwd):/usr/src \
          sonarsource/sonar-scanner-cli \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.organization=${{ secrets.SONAR_ORG }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        echo "Building Docker image with tag: $COMMIT_SHA"
        docker build -t arokyajp/arokya-cicd:$COMMIT_SHA .
        docker push arokyajp/arokya-cicd:$COMMIT_SHA

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: arokyajp/arokya-cicd:${{ env.COMMIT_SHA }}
        format: table
        exit-code: 0
        ignore-unfixed: true
        vuln-type: os,library

    - name: Start Minikube (if not running)
      run: |
        minikube status || minikube start

    - name: Configure kubectl to use Minikube
      run: |
        kubectl config use-context minikube
        kubectl cluster-info

    - name: Update Kubernetes deployment with new image
      run: |
        kubectl set image deployment/my-website my-website=arokyajp/arokya-cicd:$COMMIT_SHA
        kubectl rollout status deployment/my-website

    - name: Apply Ingress Config
      run: |
        kubectl apply -f ingress.yml
