name: CI/CD Pipeline - Static Website Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Uses the self-hosted runner on your local machine

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t arokyajp/arokya-cicd:latest .
        docker push arokyajp/arokya-cicd:latest

    - name: Start Minikube (if not running)
      run: |
        minikube status || minikube start

    - name: Configure kubectl to use Minikube
      run: |
        kubectl config use-context minikube
        kubectl cluster-info

    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yml  # Ensure you have a proper Kubernetes YAML file
        kubectl rollout restart deployment my-website
